# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "v1alpha.ImageFormat" do
    optional :type, :enum, 1, "v1alpha.ImageType"
    optional :version, :string, 2
  end
  add_message "v1alpha.Image" do
    optional :base_format, :message, 1, "v1alpha.ImageFormat"
    optional :id, :string, 2
    optional :name, :string, 3
    optional :version, :string, 4
    optional :import_timestamp, :int64, 5
    optional :manifest, :bytes, 6
    optional :size, :int64, 7
    repeated :annotations, :message, 8, "v1alpha.KeyValue"
  end
  add_message "v1alpha.Network" do
    optional :name, :string, 1
    optional :ipv4, :string, 2
    optional :ipv6, :string, 3
  end
  add_message "v1alpha.App" do
    optional :name, :string, 1
    optional :image, :message, 2, "v1alpha.Image"
    optional :state, :enum, 3, "v1alpha.AppState"
    optional :exit_code, :sint32, 4
    repeated :annotations, :message, 5, "v1alpha.KeyValue"
  end
  add_message "v1alpha.Pod" do
    optional :id, :string, 1
    optional :pid, :sint32, 2
    optional :state, :enum, 3, "v1alpha.PodState"
    repeated :apps, :message, 4, "v1alpha.App"
    repeated :networks, :message, 5, "v1alpha.Network"
    optional :manifest, :bytes, 6
    repeated :annotations, :message, 7, "v1alpha.KeyValue"
  end
  add_message "v1alpha.KeyValue" do
    optional :Key, :string, 1
    optional :value, :string, 2
  end
  add_message "v1alpha.PodFilter" do
    repeated :ids, :string, 1
    repeated :states, :enum, 2, "v1alpha.PodState"
    repeated :app_names, :string, 3
    repeated :image_ids, :string, 4
    repeated :network_names, :string, 5
    repeated :annotations, :message, 6, "v1alpha.KeyValue"
  end
  add_message "v1alpha.ImageFilter" do
    repeated :ids, :string, 1
    repeated :prefixes, :string, 2
    repeated :base_names, :string, 3
    repeated :keywords, :string, 4
    repeated :labels, :message, 5, "v1alpha.KeyValue"
    optional :imported_after, :int64, 6
    optional :imported_before, :int64, 7
    repeated :annotations, :message, 8, "v1alpha.KeyValue"
    repeated :full_names, :string, 9
  end
  add_message "v1alpha.Info" do
    optional :rkt_version, :string, 1
    optional :appc_version, :string, 2
    optional :api_version, :string, 3
  end
  add_message "v1alpha.Event" do
    optional :type, :enum, 1, "v1alpha.EventType"
    optional :id, :string, 2
    optional :from, :string, 3
    optional :time, :int64, 4
    repeated :data, :message, 5, "v1alpha.KeyValue"
  end
  add_message "v1alpha.EventFilter" do
    repeated :types, :enum, 1, "v1alpha.EventType"
    repeated :ids, :string, 2
    repeated :names, :string, 3
    optional :since_time, :int64, 4
    optional :until_time, :int64, 5
  end
  add_message "v1alpha.GetInfoRequest" do
  end
  add_message "v1alpha.GetInfoResponse" do
    optional :info, :message, 1, "v1alpha.Info"
  end
  add_message "v1alpha.ListPodsRequest" do
    repeated :filters, :message, 1, "v1alpha.PodFilter"
    optional :detail, :bool, 2
  end
  add_message "v1alpha.ListPodsResponse" do
    repeated :pods, :message, 1, "v1alpha.Pod"
  end
  add_message "v1alpha.InspectPodRequest" do
    optional :id, :string, 1
  end
  add_message "v1alpha.InspectPodResponse" do
    optional :pod, :message, 1, "v1alpha.Pod"
  end
  add_message "v1alpha.ListImagesRequest" do
    repeated :filters, :message, 1, "v1alpha.ImageFilter"
    optional :detail, :bool, 2
  end
  add_message "v1alpha.ListImagesResponse" do
    repeated :images, :message, 1, "v1alpha.Image"
  end
  add_message "v1alpha.InspectImageRequest" do
    optional :id, :string, 1
  end
  add_message "v1alpha.InspectImageResponse" do
    optional :image, :message, 1, "v1alpha.Image"
  end
  add_message "v1alpha.ListenEventsRequest" do
    optional :filter, :message, 1, "v1alpha.EventFilter"
  end
  add_message "v1alpha.ListenEventsResponse" do
    repeated :events, :message, 1, "v1alpha.Event"
  end
  add_message "v1alpha.GetLogsRequest" do
    optional :pod_id, :string, 1
    optional :app_name, :string, 2
    optional :lines, :int32, 3
    optional :follow, :bool, 4
    optional :since_time, :int64, 5
    optional :until_time, :int64, 6
  end
  add_message "v1alpha.GetLogsResponse" do
    repeated :lines, :string, 1
  end
  add_enum "v1alpha.ImageType" do
    value :IMAGE_TYPE_UNDEFINED, 0
    value :IMAGE_TYPE_APPC, 1
    value :IMAGE_TYPE_DOCKER, 2
    value :IMAGE_TYPE_OCI, 3
  end
  add_enum "v1alpha.AppState" do
    value :APP_STATE_UNDEFINED, 0
    value :APP_STATE_RUNNING, 1
    value :APP_STATE_EXITED, 2
  end
  add_enum "v1alpha.PodState" do
    value :POD_STATE_UNDEFINED, 0
    value :POD_STATE_EMBRYO, 1
    value :POD_STATE_PREPARING, 2
    value :POD_STATE_PREPARED, 3
    value :POD_STATE_RUNNING, 4
    value :POD_STATE_ABORTED_PREPARE, 5
    value :POD_STATE_EXITED, 6
    value :POD_STATE_DELETING, 7
    value :POD_STATE_GARBAGE, 8
  end
  add_enum "v1alpha.EventType" do
    value :EVENT_TYPE_UNDEFINED, 0
    value :EVENT_TYPE_POD_PREPARED, 1
    value :EVENT_TYPE_POD_PREPARE_ABORTED, 2
    value :EVENT_TYPE_POD_STARTED, 3
    value :EVENT_TYPE_POD_EXITED, 4
    value :EVENT_TYPE_POD_GARBAGE_COLLECTED, 5
    value :EVENT_TYPE_APP_STARTED, 6
    value :EVENT_TYPE_APP_EXITED, 7
    value :EVENT_TYPE_IMAGE_IMPORTED, 8
    value :EVENT_TYPE_IMAGE_REMOVED, 9
  end
end

module V1alpha
  ImageFormat = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.ImageFormat").msgclass
  Image = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.Image").msgclass
  Network = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.Network").msgclass
  App = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.App").msgclass
  Pod = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.Pod").msgclass
  KeyValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.KeyValue").msgclass
  PodFilter = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.PodFilter").msgclass
  ImageFilter = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.ImageFilter").msgclass
  Info = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.Info").msgclass
  Event = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.Event").msgclass
  EventFilter = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.EventFilter").msgclass
  GetInfoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.GetInfoRequest").msgclass
  GetInfoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.GetInfoResponse").msgclass
  ListPodsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.ListPodsRequest").msgclass
  ListPodsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.ListPodsResponse").msgclass
  InspectPodRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.InspectPodRequest").msgclass
  InspectPodResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.InspectPodResponse").msgclass
  ListImagesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.ListImagesRequest").msgclass
  ListImagesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.ListImagesResponse").msgclass
  InspectImageRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.InspectImageRequest").msgclass
  InspectImageResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.InspectImageResponse").msgclass
  ListenEventsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.ListenEventsRequest").msgclass
  ListenEventsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.ListenEventsResponse").msgclass
  GetLogsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.GetLogsRequest").msgclass
  GetLogsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.GetLogsResponse").msgclass
  ImageType = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.ImageType").enummodule
  AppState = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.AppState").enummodule
  PodState = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.PodState").enummodule
  EventType = Google::Protobuf::DescriptorPool.generated_pool.lookup("v1alpha.EventType").enummodule
end
