# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: api.proto for package 'v1alpha'

require 'grpc'
require 'api'

module V1alpha
  module PublicAPI

    # TODO: add proto service documentation here
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'v1alpha.PublicAPI'

      rpc :GetInfo, GetInfoRequest, GetInfoResponse
      rpc :ListPods, ListPodsRequest, ListPodsResponse
      rpc :InspectPod, InspectPodRequest, InspectPodResponse
      rpc :ListImages, ListImagesRequest, ListImagesResponse
      rpc :InspectImage, InspectImageRequest, InspectImageResponse
      rpc :ListenEvents, ListenEventsRequest, stream(ListenEventsResponse)
      rpc :GetLogs, GetLogsRequest, stream(GetLogsResponse)
    end

    Stub = Service.rpc_stub_class
  end
end
